### ISSUE TITLE
Updated to latest sunder and ES Modules

### ISSUE THREAD

**Issue by beckelmw** [gzuidhof/sunder-worker-template#1]
Greetings - would it be possible to update this template to the latest sunder and ES Modules. I gave it a go this morning but wasn't able to get it working.

**Comment by gzuidhof** [comment]
Hi beckelmw,

I would love to update the template, but as it stands it's not really possible to use ES Module format together with Sites in any way :(. 

I've used Sunder in a ES Module format project (including durable objects), but that meant I had to give up a working sites integration, this is the relevant PR https://github.com/cloudflare/wrangler/pull/1973, I'm not sure why there isn't any recent progress on it (it's a pretty big blocker!), of course feel free to contribute to the discussion there :).

Anyway the project lives [here](https://github.com/gzuidhof/LD49/tree/master/beamerserver), it's a bit hacky as it was a 48 hour gamejam so quality wasn't necessarily top of mind.

**Comment by beckelmw** [comment]
Thank you for the quick response and example app link. I am new to cloudflare workers and picked up some nice tidbits from your game project. I now have a project with esbuild, miniflare, and esm modules working thanks to your example.

**Comment by gzuidhof** [comment]
With the recent updates to Wrangler, Miniflare and KV-Asset-Handler we're now up to date again 🥳
