### ISSUE TITLE
Working with KV

### ISSUE THREAD

**Issue by ChrisButterworth** [gzuidhof/sunder-worker-template#11]
Added a KVNamespace to `bindings.ts` but comes up as `undefined` any guidance or examples would be great.

**Comment by gzuidhof** [comment]
Hi Chris,

There are two ways to access KV, it depends on whether you are using the ES module or the Service Worker mode - that's a wrangler/CF workers thing (i.e. not Sunder specific). https://developers.cloudflare.com/workers/cli-wrangler/configuration/#service-workers

The module mode won't have any globals, instead you use env

**Comment by ChrisButterworth** [comment]
Trying to use it as an ES module as I've written my code to use the KV API and hoped it'd be fairly straight forward to swap it to use a module instead.

Already using env but coming back with `undefined`

**Comment by ChrisButterworth** [comment]
Oddly, using `wrangler dev` when `wrangler.toml` and `bindings.d.ts` are updated seems to work. Using miniflare causes an issue - will check to ensure this is a bug.

**Comment by ChrisButterworth** [comment]
Closing this as it's an issue with miniflare not Sunder
