### ISSUE TITLE
Cannot read favicon-32x32.png

### ISSUE THREAD

**Issue by ghost** [gzuidhof/sunder-worker-template#5]
I am unable to install this template. I have tried on 2 different MacBook Pros using npm v8.3.0 and v8.1.0 and node v17.3.0 and v16.12.0. 

```shell
% wrangler generate testproject https://github.com/sunderjs/sunder-worker-template  
🔧   Creating project called `testproject`...
Error: liquid: Cannot read file
  with:
    path=/Users/jeremiah/Projects/testproject/static/favicon-32x32.png

Error: tried running command:
/Users/jeremiah/Library/Caches/.wrangler/cargo-generate-0.5.0/cargo-generate generate --git https://github.com/sunderjs/sunder-worker-template --name testproject --force
exited with exit status: 1
```

`/Users/jeremiah/Projects/testproject/static/favicon-32x32.png` does exist in Finder.

**Comment by gzuidhof** [comment]
Could you try again now? I re-added `cargo-template.toml` ([link](https://github.com/SunderJS/sunder-worker-template/blob/master/cargo-generate.toml)), I think that file was necessary to stop Cargo's templating system from trying to do string replacements in a .png file

**Comment by ghost** [comment]
I am no longer getting this error. Thanks!
